---

- name: check that the /var/log/mysqld.log exists
  stat:
    path: /var/log/mysqld.log
  register: file_result

- name: set root password
  command: |
    mysql -u"root" -p"" \
    -e "alter user 'root'@'localhost' identified with mysql_native_password by '{{ root_password }}';"
    mysql -u"root" -p"{{ root_password }}" \
    -e "flush privileges;"
  when:
    - file_result.stat.exists

- name: delete /var/log/mysqld.log
  file:
    state: absent
    path: /var/log/mysqld.log

- name: delete anonymous connections
  mysql_user:
    login_user: "{{ root_user }}"
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ percona_socket }}"
    name: ""
    host_all: yes
    state: absent

- name: secure the MySQL root user for localhost
  mysql_user:
    login_user: "{{ root_user }}"
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ percona_socket }}"
    name: "{{ root_user }}"
    host: "{{ item }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    - "{{ percona_bind_address }}"

- name: remove the MySQL test database
  mysql_db:
    db: test
    login_user: "{{ root_user }}"
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ percona_socket }}"
    state: absent
